# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official

# AndroidX
android.useAndroidX=true
android.enableJetifier=false

# Habilitar el nuevo DSL para eliminar avisos de deprecación
android.newDsl=true
android.defaults.buildfeatures.resvalues=true
